In [3]:
import pandas as pd
from sklearn import tree
from sklearn.model_selection import train_test_split

data = pd.read_csv("./BLE_RSSI_dataset/iBeacon_RSSI_Labeled.csv")
data.head()

,location,date,b3001,b3002,b3003,b3004,b3005,b3006,b3007,b3008,b3009,b3010,b3011,b3012,b3013
0,O02,10-18-2016 11:15:21,-200,-200,-200,-200,-200,-78,-200,-200,-200,-200,-200,-200,-200
1,P01,10-18-2016 11:15:19,-200,-200,-200,-200,-200,-78,-200,-200,-200,-200,-200,-200,-200
2,P01,10-18-2016 11:15:17,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200
3,P01,10-18-2016 11:15:15,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200
4,P01,10-18-2016 11:15:13,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200

In [4]:
#drop Time
newdata = data.drop(columns=['date']);
newdata.head()

,location,b3001,b3002,b3003,b3004,b3005,b3006,b3007,b3008,b3009,b3010,b3011,b3012,b3013
0,O02,-200,-200,-200,-200,-200,-78,-200,-200,-200,-200,-200,-200,-200
1,P01,-200,-200,-200,-200,-200,-78,-200,-200,-200,-200,-200,-200,-200
2,P01,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200
3,P01,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200
4,P01,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200

In [5]:
train_data=newdata[['b3001','b3002','b3003','b3004','b3005','b3006','b3007','b3008','b3009','b3010','b3011','b3012','b3013',]]
train_target=newdata[['location']]

In [6]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import  train_test_split
data_x = train_data
data_y = train_target

x_train,x_test,y_train,y_test = train_test_split(data_x,data_y,test_size=0.3)

pcl = RandomForestRegressor()

train = pcl.fit(x_train,y_train)
p = pcl.predict(x_test)
print(p)
print(type(p))
print(type(y_test))
print(y_test)

/Users/anthonymao08/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/anthonymao08/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # This is added back by InteractiveShellApp.init_path()

ValueError: could not convert string to float: 'R03'