In [2]:
import numpy as np # 快速操作结构数组的工具
from sklearn import svm  # svm支持向量机
import matplotlib.pyplot as plt # 可视化绘图
import pandas as pd

data = pd.read_csv("./BLE_RSSI_dataset/iBeacon_RSSI_Labeled.csv")
data.head()

,location,date,b3001,b3002,b3003,b3004,b3005,b3006,b3007,b3008,b3009,b3010,b3011,b3012,b3013
0,O02,10-18-2016 11:15:21,-200,-200,-200,-200,-200,-78,-200,-200,-200,-200,-200,-200,-200
1,P01,10-18-2016 11:15:19,-200,-200,-200,-200,-200,-78,-200,-200,-200,-200,-200,-200,-200
2,P01,10-18-2016 11:15:17,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200
3,P01,10-18-2016 11:15:15,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200
4,P01,10-18-2016 11:15:13,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200

In [4]:
#drop Time
newdata = data.drop(columns=['date']);
newdata.head()

,location,b3001,b3002,b3003,b3004,b3005,b3006,b3007,b3008,b3009,b3010,b3011,b3012,b3013
0,O02,-200,-200,-200,-200,-200,-78,-200,-200,-200,-200,-200,-200,-200
1,P01,-200,-200,-200,-200,-200,-78,-200,-200,-200,-200,-200,-200,-200
2,P01,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200
3,P01,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200
4,P01,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200

In [7]:
train_data=newdata[['b3001','b3002','b3003','b3004','b3005','b3006','b3007','b3008','b3009','b3010','b3011','b3012','b3013',]]
train_target=newdata[['location']]

In [21]:
# 创建模型
clf = svm.SVC(probability=True)
clf.fit(X=X_train, y=Y_train,sample_weight=None)  # 训练模型。参数sample_weight为每个样本设置权重。应对非均衡问题
result = clf.predict(X_test)  # 使用模型预测值
print('正确结果：',Y_test)
print('预测结果：',result)

/Users/anthonymao08/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/anthonymao08/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

正确结果：      location
169       M04
37        S02
512       I07
912       J07
341       K06
383       D15
435       J07
1086      I04
1023      Q05
1040      O05
223       L05
48        J03
194       J04
236       N05
863       W15
311       O06
80        O03
1163      Q04
259       Q05
830       I02
1117      L04
487       M02
101       R03
685       S08
1047      O05
1227      Q03
432       J06
572       K04
481       M01
301       Q06
...       ...
767       J04
709       L02
1078      J05
921       I04
303       P06
1233      P03
216       K05
819       I04
1318      S01
631       V15
202       I04
916       J02
989       S06
310       O06
1268      K03
653       S04
8         R01
241       O05
368       J07
494       N01
757       J02
735       K04
1062      L05
1059      M05
821       I03
275       R05
1083      I05
643       S02
994       S06
804       I08

[355 rows x 1 columns]
预测结果： ['K05' 'S01' 'I07' 'J07' 'K03' 'D15' 'K07' 'I04' 'S05' 'U04' 'O06' 'K04'
 'J04' 'O06' 'V15' 'N06' 'Q01' 'Q04' 'S01' 'I08' 'K04' 'M02' 'S02' 'S01'
 'O05' 'S01' 'J04' 'J02' 'P04' 'L02' 'P15' 'K05' 'K03' 'S05' 'K05' 'W15'
 'O05' 'K03' 'S01' 'D13' 'L04' 'K04' 'K05' 'J02' 'D13' 'S01' 'K04' 'N06'
 'K03' 'I07' 'L02' 'I07' 'K05' 'N05' 'K03' 'J02' 'N02' 'N03' 'I06' 'S05'
 'L04' 'D13' 'S05' 'N05' 'S05' 'K05' 'Q01' 'N02' 'J04' 'U04' 'J04' 'R15'
 'J06' 'I10' 'J04' 'U15' 'M01' 'L03' 'J07' 'S01' 'S01' 'I08' 'L06' 'D15'
 'S01' 'L02' 'I08' 'Q01' 'L02' 'P04' 'J02' 'J02' 'I08' 'O05' 'M01' 'L02'
 'K06' 'I08' 'M02' 'P15' 'K04' 'S01' 'K04' 'L06' 'M03' 'I08' 'I08' 'S02'
 'S01' 'S01' 'J05' 'L04' 'S05' 'J04' 'L06' 'J06' 'S01' 'S01' 'J04' 'M01'
 'I10' 'S01' 'U01' 'S06' 'L15' 'N06' 'L15' 'S01' 'D15' 'K03' 'D14' 'S05'
 'L06' 'S01' 'R15' 'S02' 'S02' 'I08' 'L02' 'K05' 'K03' 'S04' 'I08' 'O04'
 'Q04' 'I10' 'L06' 'S04' 'S01' 'T15' 'J07' 'I07' 'N15' 'I10' 'W15' 'K06'
 'I08' 'I01' 'W15' 'J02' 'K07' 'I01' 'S02' 'S07' 'N03' 'J02' 'L02' 'K04'
 'P04' 'N03' 'S01' 'J02' 'M05' 'W15' 'N02' 'J04' 'S06' 'N01' 'K06' 'D15'
 'L06' 'I01' 'M04' 'S01' 'I06' 'S02' 'J04' 'K04' 'I08' 'S02' 'I01' 'K03'
 'S05' 'J05' 'M03' 'K04' 'K04' 'K06' 'S01' 'S01' 'I08' 'K03' 'M02' 'Q05'
 'S01' 'M01' 'K03' 'J02' 'S01' 'U01' 'M06' 'R04' 'I06' 'W15' 'P04' 'L02'
 'N05' 'O05' 'J02' 'K05' 'I08' 'S05' 'S04' 'K05' 'S05' 'S05' 'K04' 'I06'
 'S05' 'U15' 'S01' 'S07' 'S01' 'I07' 'J10' 'G15' 'S01' 'S01' 'S01' 'N03'
 'I08' 'M01' 'I06' 'N03' 'L06' 'S04' 'I07' 'I07' 'K04' 'I07' 'L06' 'M06'
 'S01' 'S02' 'V15' 'S01' 'L02' 'J04' 'M04' 'K04' 'I08' 'S01' 'L06' 'K03'
 'S02' 'I02' 'L02' 'Q01' 'J05' 'J02' 'S02' 'J04' 'Q04' 'K05' 'J08' 'L02'
 'S01' 'I06' 'U01' 'K04' 'K05' 'J04' 'S04' 'I08' 'I08' 'M01' 'K05' 'S06'
 'K07' 'D15' 'K03' 'I08' 'J02' 'V15' 'Q03' 'O05' 'V15' 'K03' 'I08' 'S01'
 'D13' 'S05' 'O05' 'L06' 'N03' 'M01' 'O04' 'N02' 'S01' 'S01' 'D13' 'S01'
 'K07' 'D13' 'P04' 'N06' 'P01' 'O03' 'S02' 'I07' 'S01' 'Q04' 'L06' 'L15'
 'N03' 'J04' 'K03' 'J05' 'I04' 'P01' 'R04' 'K05' 'J06' 'S01' 'V15' 'J02'
 'K05' 'S01' 'N05' 'M01' 'Q01' 'S01' 'O05' 'J07' 'N01' 'J02' 'J02' 'Q04'
 'L06' 'I03' 'S01' 'K05' 'U01' 'S06' 'I08']